python: can't open file '/tmp/gptme-evals-_c_d82zp/prime.py': [Errno 2] No such file or directory
