python: can't open file '/tmp/gptme-evals-q4rw8fwu/prime.py': [Errno 2] No such file or directory
