python: can't open file '/tmp/gptme-evals-397xrzsm/prime.py': [Errno 2] No such file or directory
