python: can't open file '/tmp/gptme-evals-_fc2owe4/prime.py': [Errno 2] No such file or directory
