python: can't open file '/tmp/gptme-evals-a6mfvbi_/prime.py': [Errno 2] No such file or directory
