python: can't open file '/tmp/gptme-evals-qn8n_sez/prime.py': [Errno 2] No such file or directory
