python: can't open file '/tmp/gptme-evals-uhh9o65s/prime.py': [Errno 2] No such file or directory
