python: can't open file '/tmp/gptme-evals-ul3wlk9u/prime.py': [Errno 2] No such file or directory
