python: can't open file '/tmp/gptme-evals-_9c14pth/prime.py': [Errno 2] No such file or directory
