python: can't open file '/tmp/gptme-evals-9g3h3t9e/prime.py': [Errno 2] No such file or directory
