python: can't open file '/tmp/gptme-evals-105n2t6o/prime.py': [Errno 2] No such file or directory
